from bangazon_reports.views.helpers import dict_fetch_all
from bangazon_reports.views.orders.complete_orders import CompleteOrdersList
from bangazon_reports.views.orders.incomplete_orders import IncompleteOrdersList
from bangazon_reports.views.products.products_20 import TopProductList
from bangazon_reports.views.products.products_expensive import ExpensiveProductList
from bangazon_reports.views.products.products_inexpensive import InexpensiveProductList